

insert into Teams values ('Arizona', 'Cardinals')
insert into Teams values ('Atlanta', 'Falcons')
insert into Teams values ('Baltimore', 'Ravens')
insert into Teams values ('Buffalo', 'Bills')
insert into Teams values ('Carolina', 'Panthers')
insert into Teams values ('Chicago', 'Bears')
insert into Teams values ('Cincinnati', 'Bengals')
insert into Teams values ('Cleveland', 'Browns')
insert into Teams values ('Dallas', 'Cowboys')
insert into Teams values ('Denver', 'Broncos')
insert into Teams values ('Detroit', 'Lions')
insert into Teams values ('Green Bay', 'Packers')
insert into Teams values ('Houston', 'Texans')
insert into Teams values ('Indianapolis', 'Colts')
insert into Teams values ('Jacksonville', 'Jaguars')
insert into Teams values ('Kansas City', 'Chiefs')
insert into Teams values ('Los Angeles', 'Rams')
insert into Teams values ('Miami', 'Dolphins')
insert into Teams values ('Minnesota', 'Vikings')
insert into Teams values ('New England', 'Patriots')
insert into Teams values ('New Orleans', 'Saints')
insert into Teams values ('New York', 'Giants')
insert into Teams values ('New York', 'Jets')
insert into Teams values ('Oakland', 'Raiders')
insert into Teams values ('Philadelphia', 'Eagles')
insert into Teams values ('Pittsburgh', 'Steelers')
insert into Teams values ('San Diego', 'Chargers')
insert into Teams values ('San Francisco', '49ers')
insert into Teams values ('Seattle', 'Seahawks')
insert into Teams values ('Tampa Bay', 'Buccaneers')
insert into Teams values ('Tennessee', 'Titans')
insert into Teams values ('Washington', 'Redskins')